name: Build

on:
  push:
    branches-ignore:
      - gh-pages
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: JRMurr/direnv-nix-action@v4.2.0

      - name: Build
        run: |
          bun install --frozen-lockfile
          bun run build
